// Generated by IcedCoffeeScript 1.6.3-f
var iced, matcher, __iced_k, __iced_k_noop,
  __slice = [].slice;

iced = {
  Deferrals: (function() {
    function _Class(_arg) {
      this.continuation = _arg;
      this.count = 1;
      this.ret = null;
    }

    _Class.prototype._fulfill = function() {
      if (!--this.count) {
        return this.continuation(this.ret);
      }
    };

    _Class.prototype.defer = function(defer_params) {
      var _this = this;
      ++this.count;
      return function() {
        var inner_params, _ref;
        inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (defer_params != null) {
          if ((_ref = defer_params.assign_fn) != null) {
            _ref.apply(null, inner_params);
          }
        }
        return _this._fulfill();
      };
    };

    return _Class;

  })(),
  findDeferral: function() {
    return null;
  },
  trampoline: function(_fn) {
    return _fn();
  }
};
__iced_k = __iced_k_noop = function() {};

matcher = new RegExp("^http(s)?\://boards.4chan.org/([a-z]{1,3})/", 'i');

chrome.tabs.onUpdated.addListener(function(tabId, info, tab) {
  if (matcher.test(tab.url)) {
    return chrome.pageAction.show(tabId);
  }
});

chrome.tabs.onActivated.addListener(function(activeInfo) {
  var tab, ___iced_passed_deferral, __iced_deferrals, __iced_k,
    _this = this;
  __iced_k = __iced_k_noop;
  ___iced_passed_deferral = iced.findDeferral(arguments);
  (function(__iced_k) {
    __iced_deferrals = new iced.Deferrals(__iced_k, {
      parent: ___iced_passed_deferral,
      filename: "4chan-post-highlight-extension\\background.iced"
    });
    chrome.tabs.get(activeInfo.tabId(__iced_deferrals.defer({
      assign_fn: (function() {
        return function() {
          return tab = arguments[0];
        };
      })(),
      lineno: 6
    })));
    __iced_deferrals._fulfill();
  })(function() {
    if (matcher.test(tab.url)) {
      return chrome.pageAction.show(tab.Id);
    }
  });
});
